[tool.poetry]
name = "jlj-utils"
version = "0.1.0"
description = "my personal utilities"
authors = ["jowj <me@jowj.net>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
